// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'TODO: Removida por segurança',
    appId: '1:680050997560:web:7d82da75b6d2daebf069cd',
    messagingSenderId: '680050997560',
    projectId: 'gestao101-4d1cd',
    authDomain: 'gestao101-4d1cd.firebaseapp.com',
    storageBucket: 'gestao101-4d1cd.firebasestorage.app',
    measurementId: 'G-SRC0F32SLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'TODO: Removida por segurança',
    appId: '1:680050997560:android:fd6b2593f816945cf069cd',
    messagingSenderId: '680050997560',
    projectId: 'gestao101-4d1cd',
    storageBucket: 'gestao101-4d1cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'TODO: Removida por segurança',
    appId: '1:680050997560:ios:9d466a9d49639618f069cd',
    messagingSenderId: '680050997560',
    projectId: 'gestao101-4d1cd',
    storageBucket: 'gestao101-4d1cd.firebasestorage.app',
    iosBundleId: 'com.example.gestaoSalasEquipamentos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'TODO: Removida por segurança',
    appId: '1:680050997560:ios:9d466a9d49639618f069cd',
    messagingSenderId: '680050997560',
    projectId: 'gestao101-4d1cd',
    storageBucket: 'gestao101-4d1cd.firebasestorage.app',
    iosBundleId: 'com.example.gestaoSalasEquipamentos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'TODO: Removida por segurança',
    appId: '1:680050997560:web:348c18fe0be4dfa4f069cd',
    messagingSenderId: '680050997560',
    projectId: 'gestao101-4d1cd',
    authDomain: 'gestao101-4d1cd.firebaseapp.com',
    storageBucket: 'gestao101-4d1cd.firebasestorage.app',
    measurementId: 'G-966RTKSX5X',
  );
}
